import React, { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Sparkles } from 'lucide-react';
import { Product } from '../types';
import { handleImageError } from '../utils/imageFallback';

interface HeroSectionProps { featuredProduct: Product; onQuickView: (product: Product) => void; onShopNow: (category?: string) => void; }
type Slide = { eyebrow: string; title: string; accent: string; description: string; primary: string; secondary: string; category: string; discount: string; image: string; accents: string[]; productName: string; };

const slides: Slide[] = [
  { eyebrow: 'THE BRIDAL COLLECTION', title: 'Vows Worth a Lifetime,', accent: 'Jewels Worth Forever.', description: 'Heirloom diamonds and luminous gold, crafted for every chapter that follows “I do”.', primary: 'Shop Bridal Collection', secondary: 'Discover Bridal', category: 'Bridal', discount: 'BIS HALLMARKED', image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1200&q=85', accents: ['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=500&q=80', 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=500&q=80'], productName: 'The Devika Bridal Edit' },
  { eyebrow: 'NEW DIAMOND ARRIVALS', title: 'Brilliance,', accent: 'Redefined.', description: 'Modern diamond essentials with unmistakable sparkle, designed to become part of you.', primary: 'Explore New Arrivals', secondary: 'Shop Diamond Rings', category: 'Rings', discount: 'IGI CERTIFIED', image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=85', accents: ['https://images.unsplash.com/photo-1635767798638-3e25273a8236?auto=format&fit=crop&w=500&q=80', 'https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=500&q=80'], productName: 'The Celeste Diamond Collection' },
  { eyebrow: 'THE GOLD COLLECTION', title: 'Timeless Gold,', accent: 'Modern Grace.', description: 'Fluid silhouettes and the warm glow of gold for rituals, milestones and every day.', primary: 'Shop Gold Collection', secondary: 'Explore Necklaces', category: 'Necklaces', discount: '22K GOLD', image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=85', accents: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=500&q=80', 'https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=500&q=80'], productName: 'The Lumière Gold Edit' },
  { eyebrow: 'THE CELEBRATION EDIT', title: 'Celebrate in', accent: 'Radiance.', description: 'A considered selection of gifts, gemstones and luminous pieces for every special moment.', primary: 'Shop the Celebration Edit', secondary: 'Discover Gemstones', category: 'Gemstones', discount: 'UP TO 20% OFF', image: 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=1200&q=85', accents: ['https://images.unsplash.com/photo-1635767798638-3e25273a8236?auto=format&fit=crop&w=500&q=80', 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=500&q=80'], productName: 'The Gifting Collection' }
];

export const HeroSection: React.FC<HeroSectionProps> = ({ featuredProduct, onQuickView, onShopNow }) => {
  const [active, setActive] = useState(0); const [paused, setPaused] = useState(false); const [reducedMotion, setReducedMotion] = useState(false); const touchStart = useRef<number | null>(null);
  const activeSlide = slides[active];
  const goTo = useCallback((next: number) => setActive((next + slides.length) % slides.length), []);
  const move = useCallback((direction: number) => setActive((current) => (current + direction + slides.length) % slides.length), []);
  useEffect(() => { const media = window.matchMedia('(prefers-reduced-motion: reduce)'); const update = () => setReducedMotion(media.matches); update(); media.addEventListener('change', update); return () => media.removeEventListener('change', update); }, []);
  useEffect(() => { slides.forEach((slide) => [slide.image, ...slide.accents].forEach((src) => { const image = new Image(); image.src = src; })); }, []);
  useEffect(() => { if (paused || reducedMotion) return; const timer = window.setInterval(() => move(1), 5500); return () => window.clearInterval(timer); }, [move, paused, reducedMotion]);

  return <section aria-roledescription="carousel" aria-label="Featured collections" className="relative min-h-[720px] lg:min-h-[calc(100vh-5rem)] flex items-center overflow-hidden bg-[#0c0c0d] text-white" onMouseEnter={() => setPaused(true)} onMouseLeave={() => setPaused(false)} onFocusCapture={() => setPaused(true)} onBlurCapture={() => setPaused(false)} onTouchStart={(event) => { touchStart.current = event.touches[0].clientX; }} onTouchEnd={(event) => { if (touchStart.current === null) return; const delta = event.changedTouches[0].clientX - touchStart.current; if (Math.abs(delta) > 45) move(delta > 0 ? -1 : 1); touchStart.current = null; }}>
    <div className="absolute inset-0 opacity-30 pointer-events-none" style={{ backgroundImage: 'radial-gradient(circle at 78% 45%, rgba(212,175,55,.23), transparent 28%), radial-gradient(circle at 15% 14%, rgba(255,255,255,.08), transparent 24%)' }} />
    <div className="relative z-10 grid w-full max-w-[1440px] mx-auto grid-cols-1 items-center gap-12 px-5 py-16 md:px-10 lg:grid-cols-2 lg:gap-16 lg:px-14">
      <div className="max-w-2xl"><div key={`copy-${active}`} className="hero-slide-enter">
        <p className="mb-6 text-[11px] font-bold tracking-[.22em] text-[#f4b41a] uppercase">{activeSlide.eyebrow}</p>
        <h1 className="font-serif text-5xl font-semibold leading-[.98] tracking-tight sm:text-6xl lg:text-7xl xl:text-8xl">{activeSlide.title}<br /><span className="text-[#f4b41a] italic font-normal">{activeSlide.accent}</span></h1>
        <p className="mt-6 max-w-xl text-base leading-relaxed text-[#aeb8c5] sm:text-lg">{activeSlide.description}</p>
        <div className="mt-8 flex flex-wrap gap-3"><button onClick={() => onShopNow(activeSlide.category)} className="rounded-full bg-[#f4b41a] px-6 py-3.5 text-sm font-bold text-[#0b1622] transition hover:bg-[#ffd05d] focus:outline-none focus:ring-2 focus:ring-[#f4b41a] focus:ring-offset-2 focus:ring-offset-[#0b1622]">{activeSlide.primary} <ArrowRight className="ml-1 inline h-4 w-4" /></button><button onClick={() => onShopNow(activeSlide.category)} className="rounded-full border border-white/30 bg-white/5 px-6 py-3.5 text-sm font-semibold text-white transition hover:border-[#f4b41a] hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-[#f4b41a]">{activeSlide.secondary}</button></div>
        <div className="mt-12 flex items-center gap-3 text-sm text-[#c8d0db]"><div className="flex -space-x-3" aria-hidden="true">{['1535713875002-d1d0cf377fde', '1494790108377-be9c29b29330', '1500648767791-00dcc994a43e'].map((id) => <img key={id} src={`https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=80&q=80`} alt="" className="h-9 w-9 rounded-full border-2 border-[#101b2c] object-cover" />)}</div><span>Join <strong className="font-semibold text-white">15,000+</strong> happy customers</span></div>
      </div></div>
      <div className="relative mx-auto w-full max-w-[530px] lg:mr-0"><div key={`image-${active}`} className="hero-image-enter relative aspect-[4/5] sm:aspect-[5/4] lg:aspect-[4/5]"><div className="absolute inset-3 rounded-[2rem] bg-[#f4b41a]/25 -rotate-3" /><div className="absolute inset-0 overflow-hidden rounded-[2rem] border border-white/15 bg-[#d1ae67]/30 shadow-2xl"><img src={activeSlide.image} alt={`${activeSlide.productName} collection`} onError={handleImageError} className="h-full w-full object-cover" /><div className="absolute inset-x-0 bottom-0 h-1/3 bg-gradient-to-t from-[#0b1622]/70 to-transparent" /><div className="absolute bottom-5 left-5 right-5 flex items-center justify-between rounded-2xl border border-white/15 bg-[#0b1622]/80 p-4 backdrop-blur"><span><span className="flex items-center gap-1 text-[10px] font-bold tracking-wider text-[#f4b41a]"><Sparkles className="h-3 w-3" /> CURATED FOR YOU</span><span className="mt-1 block text-sm font-semibold">{activeSlide.productName}</span></span><button onClick={() => onQuickView(featuredProduct)} className="rounded-full border border-[#f4b41a]/60 px-3 py-2 text-xs font-semibold text-[#f4b41a] hover:bg-[#f4b41a] hover:text-[#0b1622]">View</button></div></div>{activeSlide.accents.map((image, index) => <img key={image} src={image} alt="" aria-hidden="true" className={`absolute h-24 w-24 rounded-2xl border-4 border-[#101b2c] object-cover shadow-xl sm:h-28 sm:w-28 ${index === 0 ? '-bottom-7 -left-7 rotate-[-8deg]' : '-right-5 bottom-12 rotate-[8deg]'}`} />)}<div className="absolute -right-5 -top-5 grid h-24 w-24 place-content-center rounded-full border-[5px] border-[#101b2c] bg-[#f4b41a] p-2 text-center text-[10px] font-bold leading-tight text-[#0b1622] shadow-xl">{activeSlide.discount}</div></div></div>
    </div>
    <button aria-label="Previous slide" onClick={() => move(-1)} className="absolute left-3 top-1/2 z-20 hidden -translate-y-1/2 rounded-full border border-white/30 bg-[#0b1622]/70 p-3 text-white transition hover:border-[#f4b41a] hover:bg-[#f4b41a] hover:text-[#0b1622] focus:outline-none focus:ring-2 focus:ring-[#f4b41a] md:block"><ArrowLeft className="h-5 w-5" /></button><button aria-label="Next slide" onClick={() => move(1)} className="absolute right-3 top-1/2 z-20 hidden -translate-y-1/2 rounded-full border border-white/30 bg-[#0b1622]/70 p-3 text-white transition hover:border-[#f4b41a] hover:bg-[#f4b41a] hover:text-[#0b1622] focus:outline-none focus:ring-2 focus:ring-[#f4b41a] md:block"><ArrowRight className="h-5 w-5" /></button>
    <div className="absolute bottom-7 left-1/2 z-20 flex -translate-x-1/2 items-center gap-2" role="tablist" aria-label="Choose a featured collection">{slides.map((slide, index) => <button key={slide.category} role="tab" aria-selected={active === index} aria-label={`Show ${slide.secondary}`} onClick={() => goTo(index)} className={`h-2 rounded-full transition-all duration-300 focus:outline-none focus:ring-2 focus:ring-[#f4b41a] ${active === index ? 'w-8 bg-[#f4b41a]' : 'w-2 bg-[#8a97a8]'}`} />)}</div>
  </section>;
};
